# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  config_file_b64:
    default: ""
    description: >
      Wireguard configuration file (see #TODO for more details).
    type: string
  server_port:
    default: 52711
    description:
    type: int
